# Generated by Django 5.1.2 on 2024-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('genre_type', models.CharField(choices=[('love', 'love'), ('horror', 'horror'), ('drama', 'drama')], default='love', max_length=200)),
            ],
        ),
    ]
